### ISSUE TITLE
Package naming is unconventional

### ISSUE THREAD

**Issue by davidbkemp** [szpon/GroceryShop#1]
This doesn't really matter terribly much to me, but I suspect this is the sort of thing that can irritate those that care about this stuff.

It is conventional for package names to start with a "reverse" domain name. e.g. You will `org.apache` instead of `apache.org`.  So instead of `einsport.com.au`, I would expect to see `au.com.einsporn`.

However, unless you actually own the domain name, I would just drop the `au.com` and use `einsport` as your top level package name.

**Comment by szpon** [comment]
will do Thanks
